In [ ]:
"""
NAME: AYUSH SHARMA
REGN. NO. : 24-27-13
PROGRAMME: M.TECH DATA SCIENCE
"""

In [11]:
""" 
Q1.
a) Create a variable named var1 that stores an array of numbers from 0 to 30,
inclusive. Print var1 and its shape. Hint : arange
b) Change var2 to a validly-shaped two-dimensional matrix and store it in a
new variable called var2. Print var2 and its shape. Hint: Use the reshape function
c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
Print var3 and its shape.
d) Use two-dimensional array indexing to set the first value in the second row of var2
to -1. Now look at var1 and var3. Did they change? Explain what’s
going on. (Hint: does reshape return a view or a copy?)
e) Another thing that comes up a lot with array shapes is thinking about how to
aggregate over specific dimensions. Figure out how the NumPy sum function
works (and the axis argument in particular) and do the following:
(i) Sum var3 over its second dimension and print the result.
(ii) Sum var3 over its third dimension and print the result.
(iii) Sum var3 over both its first and third dimensions and print the result.
f) Write code to do the following:
(i) Slice out the second row of var2 and print it.
(ii) Slice out the last column of var2 using the -1 notation and print it.
(iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
"""
import numpy as np

# a) Create a variable named var1 that stores an array of numbers from 0 to 30, inclusive.
var1 = np.arange(30)
print(var1)
print(var1.shape)

# b) Change var2 to a validly-shaped two-dimensional matrix and store it in a new variable called var2.
var2 = var1.reshape(6, 5)  # Reshaping to 7 rows and 5 columns
print(var2)
print(var2.shape)

# c) Create a third variable, var3 that reshapes it into a valid three-dimensional shape.
var3 = var1.reshape(3, 5, 2)  # Reshaping to 3 layers, each with 5 rows and 2 columns
print(var3)
print(var3.shape)

# d) Use two-dimensional array indexing to set the first value in the second row of var2 to -1.
var2[1, 0] = -1
print("Updated var2:\n", var2)
print("var1 after updating var2:\n", var1)
print("var3 after updating var2:\n", var3)

# Explanation
"""
The changes made to var2 do not affect var1 or var3 because the reshape function returns a view of the original array only if possible. 
In this case, since var2 was created from var1, modifying it does not change the original data in var1, nor does it affect var3.
"""

# e) Using NumPy sum function with axis argument
# (i) Sum var3 over its second dimension and print the result.
sum_var3_axis1 = np.sum(var3, axis=1)
print("Sum of var3 over its second dimension:\n", sum_var3_axis1)

# (ii) Sum var3 over its third dimension and print the result.
sum_var3_axis2 = np.sum(var3, axis=2)
print("Sum of var3 over its third dimension:\n", sum_var3_axis2)

# (iii) Sum var3 over both its first and third dimensions and print the result.
sum_var3_axis0_and_2 = np.sum(var3, axis=(0, 2))
print("Sum of var3 over both first and third dimensions:\n", sum_var3_axis0_and_2)

# f) Slicing operations
# (i) Slice out the second row of var2 and print it.
second_row_var2 = var2[1]
print("Second row of var2:\n", second_row_var2)

# (ii) Slice out the last column of var2 using the -1 notation and print it.
last_column_var2 = var2[:, -1]
print("Last column of var2:\n", last_column_var2)

# (iii) Slice out the top right 2 × 2 submatrix of var2 and print it.
top_right_submatrix = var2[:2, -2:]
print("Top right 2x2 submatrix of var2:\n", top_right_submatrix)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
(30,)
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
(6, 5)
[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
(3, 5, 2)
Updated var2:
 [[ 0  1  2  3  4]
 [-1  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]
 [25 26 27 28 29]]
var1 after updating var2:
 [ 0  1  2  3  4 -1  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
var3 after updating var2:
 [[[ 0  1]
  [ 2  3]
  [ 4 -1]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]

 [[20 21]
  [22 23]
  [24 25]
  [26 27]
  [28 29]]]
Sum of var3 over its second dimension:
 [[ 20  19]
 [ 70  75]
 [120 125]]
Sum of var3 over its third dimension:
 [[ 1  5  3 13 17]
 [21 25 29 33 37]
 [41 45 49 53 57]]
Sum of var3 over both fi

In [13]:
"""
Q2. a) The most basic kind of broadcast is with a scalar, in which you can perform a
binary operation (e.g., add, multiply, ...) on an array and a scalar, the effect is to
perform that operation with the scalar for every element of the array. To try this
out, create a vector 1, 2, . . . , 10 by adding 1 to the result of the arange function.
b) Now, create a 10 × 10 matrix A in which Ai j = i + j. You’ll be able to do this
using the vector you just created, and adding it to a reshaped version of itself.
c) A very common use of broadcasting is to standardize data, i.e., to make it have
zero mean and unit variance. First, create a fake “data set” with 50 examples,
each with five dimensions.
import numpy.random as npr
data = np.exp(npr.randn ( 50 , 5 ) )
d) You don’t worry too much about what this code is doing at this stage of the
course, but for completeness: it imports the NumPy random number generation
library, then generates a 50 × 5 matrix of standard normalrandom variates and 
exponentiates them. The effect of this is to have a pretend
data set of 50 independent and identically-distributed vectors from a log-normal
distribution.
e) Now, compute the mean and standard deviation of each column. This should
result in two vectors of length 5. You’ll need to think a little bit about how to use
the axis argument to mean and std. Store these vectors into variables and print
both of them.
f) Now standardize the data matrix by 1) subtracting the mean off of each column,
and 2) dividing each column by its standard deviation. Do this via broadcasting,
and store the result in a matrix called normalized. To verify that you successfully
did it, compute the mean and standard deviation of
the columns of normalized and print them out.
"""
import numpy as np

# Create a vector from 0 to 9 and add 1
vector = np.arange(10) + 1
print(vector)

# Create the matrix A
A = vector[:, np.newaxis] + vector
print(A)

import numpy.random as npr

# Generate data from a log-normal distribution
data = np.exp(npr.randn(50, 5))
print(data)

# Compute mean and standard deviation along columns
mean = data.mean(axis=0)
std_dev = data.std(axis=0)

print("Mean:", mean)
print("Standard Deviation:", std_dev)

# Standardize the data
normalized = (data - mean) / std_dev

# Verify by computing mean and std of normalized data
normalized_mean = normalized.mean(axis=0)
normalized_std_dev = normalized.std(axis=0)

print("Normalized Mean:", normalized_mean)
print("Normalized Standard Deviation:", normalized_std_dev)

[ 1  2  3  4  5  6  7  8  9 10]
[[ 2  3  4  5  6  7  8  9 10 11]
 [ 3  4  5  6  7  8  9 10 11 12]
 [ 4  5  6  7  8  9 10 11 12 13]
 [ 5  6  7  8  9 10 11 12 13 14]
 [ 6  7  8  9 10 11 12 13 14 15]
 [ 7  8  9 10 11 12 13 14 15 16]
 [ 8  9 10 11 12 13 14 15 16 17]
 [ 9 10 11 12 13 14 15 16 17 18]
 [10 11 12 13 14 15 16 17 18 19]
 [11 12 13 14 15 16 17 18 19 20]]
[[ 3.8278175   0.7891186   2.82260618  1.33665765  0.39815887]
 [ 2.53212802  0.71850526  4.98400493  1.78000698  0.65064277]
 [ 1.44788001  0.6752252   1.32360222  0.81136077  1.80803196]
 [ 1.03045762  0.30044556  0.43097653  1.24230517  1.91733417]
 [ 1.64229237  4.86295167  5.9192667   1.09035783  2.27545062]
 [ 0.18076143  0.33911002  1.44617505  0.33880085  0.92551953]
 [ 0.98003353  0.76216306  5.58355792  1.20997463  1.43787406]
 [ 1.10585402  2.30365878  0.16118022  0.32227101  1.57202246]
 [ 0.50113437  0.11978464  0.30926329  1.91735602  2.67061829]
 [ 1.33397861  1.63060701  1.84014169  1.29817151  0.69168195]
 [ 0.40

In [15]:
"""
Q3. a) A Vandermonde matrix is a matrix generated from a vector in which each column
of the matrix is an integer power starting from zero. So, if I have a column vector
[x1, x2, . . . , xN]
T
, then the associated (square) Vandermonde matrix would be  
V=[[1,X1,X1^2,X1^3,......X1^(n-1)],
   [1,X2,X2^2,X2^3,......,X2^(n-1)],
   ...............................,
   [1,Xn,Xn^2,Xn^3,......,Xn^(n-1)]]                                                                                                 Use what you learned about broadcasting in the previous problem to write a
function that will produce a Vandermonde matrix for a vector [1, 2, . . . ,N]T
for

any N. Do it without using a loop. Here’s a stub to get you started:
def vandermonde (N):
vec = np.arange (N) +1
# write your code here .
Use your function for N = 12, store it in variable named vander, and print the
result.
b) Now, let’s make a pretend linear system problem with this matrix. Create a vector
of all ones, of length 12 and call it x. Perform a matrix-vector multiplication of
vander with the vector you just created and store that in a new vector and call it b.
Print the vector b.
c) First, solve the linear system the naïve way, pretending like you don’t know x.
Import numpy.linalg, invert V and multiply it by b. Print out your result. What
should you get for your answer? If the answer is different than what you
expected, write a sentence about that difference.
d) Now, solve the same linear system using solve. Print out the result. Does it seem
more or less in line with what you’d expect?
"""
#(a)
import numpy as np

def vandermonde(N):
    vec = np.arange(N) + 1
    return np.vander(vec, increasing=True)

vander = vandermonde(12)
print(vander)

#(b)
x = np.ones(12)
b = np.dot(vander, x)
print(b)

#(c)
V_inv = np.linalg.inv(vander)
result_naive = np.dot(V_inv, b)
print(result_naive)

#(d)
result_solve = np.linalg.solve(vander, b)
print(result_solve)




[[          1           1           1           1           1           1
            1           1           1           1           1           1]
 [          1           2           4           8          16          32
           64         128         256         512        1024        2048]
 [          1           3           9          27          81         243
          729        2187        6561       19683       59049      177147]
 [          1           4          16          64         256        1024
         4096       16384       65536      262144     1048576     4194304]
 [          1           5          25         125         625        3125
        15625       78125      390625     1953125     9765625    48828125]
 [          1           6          36         216        1296        7776
        46656      279936     1679616    10077696    60466176   362797056]
 [          1           7          49         343        2401       16807
       117649      823543     57